select * from CNTLIST;


-- create view CNTLIST as
SELECT ACC.ACCOUNT_NO           NO,
       B.BOOK_DATE           AS Rdate,
       B.BOOK_BALANCE        AS Rval,
       ACM.BOOK_ACM_VALUE    AS Ramass,
       ACM.REVERSE_ACM_VALUE AS Vamass,
       ACM.OFFSET_ACM_VALUE  AS Tamass
FROM CPM_BOOK_UNIT ACC
         JOIN CPM_ACC_INTR INTR ON ACC.ACCOUNT_ID = INTR.ACCOUNT_ID
         LEFT JOIN CPM_BALANCE B ON B.ACCOUNT_ID = ACC.ACCOUNT_ID
         LEFT JOIN CPM_ACM ACM ON ACM.AIT_ID = INTR.AIT_ID AND ACM.BOOK_DATE = B.BOOK_DATE
;

/*
CREATE TABLE CNTLIST(
    NO VARCHAR2(24) NOT NULL,
    RDATE DATE NOT NULL,
    RVAL NUMBER(16,2) NOT NULL,
    RAMASS NUMBER(16,2) NOT NULL,
    VAMASS NUMBER(16,2) NOT NULL,
    TAMASS NUMBER(16,2) NOT NULL
);

COMMENT ON TABLE CNTLIST IS '控制清单视图;create view CNTLIST as
SELECT ACC.ACCOUNT_NO           NO,
       B.BOOK_DATE           AS Rdate,
       B.BOOK_BALANCE        AS Rval,
       ACM.BOOK_ACM_VALUE    AS Ramass,
       ACM.REVERSE_ACM_VALUE AS Vamass,
       ACM.OFFSET_ACM_VALUE  AS Tamass
FROM CPM_BOOK_UNIT ACC
         JOIN CPM_ACC_INTR INTR ON ACC.ACCOUNT_ID = INTR.ACCOUNT_ID
         LEFT JOIN CPM_BALANCE B ON B.ACCOUNT_ID = ACC.ACCOUNT_ID
         LEFT JOIN CPM_ACM ACM ON ACM.AIT_ID = INTR.AIT_ID AND ACM.BOOK_DATE = B.BOOK_DATE
;';
COMMENT ON COLUMN CNTLIST.NO IS '账号';
COMMENT ON COLUMN CNTLIST.RDATE IS '计息日';
COMMENT ON COLUMN CNTLIST.RVAL IS '余额';
COMMENT ON COLUMN CNTLIST.RAMASS IS '余额积数';
COMMENT ON COLUMN CNTLIST.VAMASS IS '起息日调整';
COMMENT ON COLUMN CNTLIST.TAMASS IS '积数调整数';
*/
