
-- 无数据
select * from AIMS_ASSOCIATEBANK;

-- ddl
-- auto-generated definition
create table AIMS_ASSOCIATEBANK
(
    ASSID             NUMBER not null,
    ISABROAD          VARCHAR2(2),
    INFBANK           VARCHAR2(2),
    BANKCODE          VARCHAR2(32),
    ASSOCIATEBANKCODE VARCHAR2(32),
    ASSOCIATEBANKNAME VARCHAR2(255),
    COUNTRYNO         VARCHAR2(16),
    REGNO             VARCHAR2(12),
    ENGLISHNAME       VARCHAR2(256),
    SWIFTCODE         VARCHAR2(64),
    CONTACT           VARCHAR2(256),
    TELPHONE          VARCHAR2(32),
    CNADDRESS         VARCHAR2(256),
    ENADDRESS         VARCHAR2(256),
    REMARK            VARCHAR2(500),
    FILEREMARK        VARCHAR2(500),
    CREATE_TIME       DATE,
    CREATE_DWTIME     TIMESTAMP(6) default sysdate,
    UPDATE_TIME       DATE
)
;

-- 来kettle ktr ODS_AIMS_ASSOCIATEBANK.ktr ods梳理10 个
-- 来源核心表
select ASSID
,ISABROAD
,INFBANK
,BANKCODE
,ASSOCIATEBANKCODE
,ASSOCIATEBANKNAME
,COUNTRYNO
,REGNO
,ENGLISHNAME
,SWIFTCODE
,CONTACT
,TELPHONE
,CNADDRESS
,ENADDRESS
,REMARK
,FILEREMARK
,CREATE_TIME
--,CREATE_DWTIME
,UPDATE_TIME
from AIMS_ASSOCIATEBANK;
