

/*CNTLIST
V_CPM_ACCOUNT
V_CPM_BKUNIT_SBUNIT
V_CPM_TX_ATX
V_CPM_TX_VTX*/


select * from CNTLIST;


-- create view CNTLIST as
SELECT ACC.ACCOUNT_NO NO,
       B.BOOK_DATE AS Rdate,
       B.BOOK_BALANCE AS Rval,
       ACM.BOOK_ACM_VALUE AS Ramass,
       ACM.REVERSE_ACM_VALUE AS Vamass,
       ACM.OFFSET_ACM_VALUE AS Tamass
FROM CPM_BOOK_UNIT ACC
     JOIN CPM_ACC_INTR INTR ON ACC.ACCOUNT_ID = INTR.ACCOUNT_ID
     LEFT JOIN CPM_BALANCE B ON B.ACCOUNT_ID = ACC.ACCOUNT_ID
     LEFT JOIN CPM_ACM ACM ON ACM.AIT_ID = INTR.AIT_ID AND ACM.BOOK_DATE = B.BOOK_DATE
;

