

select * from V_CPM_BKUNIT_SBUNIT;

create view V_CPM_BKUNIT_SBUNIT as
select
  a.ACCOUNT_ID,
  a.SUBJECT_ID,
  a.CUR_CODE,
  a.BRANCH_NO,
  a.BTY_ID,
  a.SMART_BTY_ID,
  a.ACCOUNT_NO,
  a.ACCOUNT_NAME,
  a.BIZ_CODE,
  a.ACCOUNT_STATE,
  a.SETTLE_UP,
  a.OPEN_DATE,
  a.END_DATE,
  a.CLEAR_DATE,
  a.INIT_BALANCE,
  a.INIT_DATE,
  a.IS_OVERDUE,
  a.IS_POSTPONE,
  a.POSTPONE_DATE,
  a.TX_OP_CODE,
  a.CONTRACT_NO,
  a.REMARK,
  a.FREEZE_SDATE,
  a.FREEZE_EDATE,
  a.VERSION_COLUMN,
  b.CPM_ACCOUNT_ID,
  b.SB_UNIT_TYPE,
  b.BIZ_COMMON,
  b.TREAT_WAY,
  b.PRIOR_UNIT_ID,
  b.ACC_CLASS,
  b.OVER_DATE,
  b.EXTEND_FLAG
from CPM_BOOK_UNIT a  join CPM_SB_UNIT b  on a.ACCOUNT_ID=b.ACCOUNT_ID
/

