select * from V_CPM_TX_VTX;


create view V_CPM_TX_VTX as
select
    a.TX_ID          ,
    a.CHANNEL_ID     ,
    a.TX_TYPE_ID      ,
    a.CUR_CODE   ,
    a.BRANCH_NO   ,
    a.CREATE_BR_NO,
    a.SOURCE_ID      ,
    a.SOURCE_PROMOTER,
    a.PRIOR_TXID    ,
    a.TX_DATE        ,
    a.EXEC_RESULT    ,
    a.ERROR_CODE     ,
    a.ERROR_TEXT     ,
    a.TX_REFCODE    ,
    a.TX_ABSTRACT    ,
    a.TX_COMMENT     ,
    a.TX_STATE       ,
    a.TX_CLEAR_STATE ,
    a.TX_CLEAR_RESULT ,
    a.EXECUTE_FLAG      ,
    a.SUCC_BIZ_CODE  ,
    a.TX_FINGER_PRINT ,
    a.VCH_UDC        ,
    a.TX_CLASS        ,
    a.SPECIAL_TX_FLAG     ,
    a.BIZ_FLOW_CASE_ID,
    a.VERSION_COLUMN     ,
    b.TX_ID as VTX_ID      ,
    b.CUST_NO          ,
    b.ACC_NO               ,
    b.BIZ_ACC_NO           ,
    b.OP_CUST_NO           ,
    b.OP_ACC_NO            ,
    b.OP_BIZ_ACC_NO        ,
    b.THRD_CUST_NO         ,
    b.THRD_ACC_NO          ,
    b.THRD_BIZ_ACC_NO      ,
    b.EBK_NO          ,
    b.EBK_NAME        ,
    b.EBK_BRANCH_NAME ,
    b.EBK_BRANCH_NO   ,
    b.EBK_RIGION    ,
    b.EBK_CITY        ,
    b.EBK_ACC_NO      ,
    b.EBK_ACCOUNT_NAME    ,
    b.EBK_CNAPS_CODE  ,
    b.BC_CHANNEL           ,
    b.BC_NAME              ,
    b.BC_ACC_INDEX         ,
    b.BC_TICKET_TYPE       ,
    b.BC_TICKET_NO         ,
    b.BC_TICKET_PSWD       ,
    b.CR_DB                ,
    b.AMOUNT               ,
    b.AMOUNT2              ,
    b.INTR_AMOUNT          ,
    b.CHARGE_AMOUNT        ,
    b.START_DATE           ,
    b.END_DATE             ,
    b.INTR_RATE            ,
    b.INTR_RATE2           ,
    b.ARTICLE              ,
    b.PRICE                ,
    b.QUANTITY             ,
    b.QUANTITY_UNIT        ,
    b.DUE_INTR_RATE        ,
    b.INTR_RULE            ,
    b.DAY_UP_DOWN          ,
    b.CHARGE_RATE          ,
    b.RECONCILE_MARK       ,
    b.X_CASE_TYPE          ,
    b.X_CASE_ID            ,
    b.X_AMOUNT             ,
    b.X_START_DATE         ,
    b.X_END_DATE           ,
    b.IMG_LOC              ,
    b.TICKET_TYPE          ,
    b.TICKET_NO            ,
    b.TICKET_NOE           ,
    b.TICKET_PSWD          ,
    b.OWNED_BRANCH_NO      ,
    b.TICKET_TAKER         ,
    b.LBK_NO               ,
    b.LBK_NAME             ,
    b.LBK_BRANCH_NAME      ,
    b.LBK_BRANCH_NO        ,
    b.LBK_REGION           ,
    b.LBK_CITY             ,
    b.LBK_ACC_NO           ,
    b.LBK_ACC_NAME         ,
    b.BC_ACC               ,
    b.INTR_DATE            ,
    b.INTEREST_BEAR_WAY    ,
    b.TREAT_WAY            ,
    b.BUSNISS_TYPE         ,
    b.SMART_BTY_ID         ,
    b.TX_BIZNUMBER         ,
    b.SB_UNIT_NO           ,
    b.VCH_REF_NO           ,
    b.FLOATING_MODE        ,
    b.FLOATING_AMOUNT      ,
    b.URGENT_LEVEL         ,
    b.RESERVE_ID           ,
    b.DB_CASH_FLOW         ,
    b.CR_CASH_FLOW         ,
    b.STD_BOOK_TYPE        ,
    b.BRANCH_SORT          ,
    b.ISCA_PAY_INTR_ACC_NO ,
    b.ISCA_REC_INTR_ACC_NO ,
    b.PRO_PAY_INTR_ACC_NO  ,
    b.PRO_REC_INTR_ACC_NO  ,
    a.INPUTER              ,
    a.INPUTER_NAME         ,
    a.CHECKER              ,
    a.CHECKER_NAME         ,
    a.RATIFIER             ,
    a.RATIFIER_NAME        ,
    a.INPUT_TIME           ,
    a.CHECK_TIME           ,
    a.RATIFY_TIME		 ,
    b.ACCOUNT_NAME         ,
    b.OP_ACCOUNT_NAME,
    b.USE_OF_FUNDS
from CPM_TX a  join CPM_VTX b  on a.tx_id=b.tx_id
/